name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setting up python 2.X
    - uses: actions/setup-python@v1
      with:
        python-version: '2.x' 
        architecture: 'x64' 
    - name: Installing wheel package for pip # This makes the warning about legacy installing go away. 
    - uses: BSFishy/pip-action@v1
      with:
        packages: wheel
    - name: Installing pyxform # This makes the warning about legacy installing go away. 
    - uses: BSFishy/pip-action@v1
      with:
        packages: git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
    - run: npm ci
    - run: npm test
      env:
        CI: true